# use oficial image PostgreSQL as base image
FROM postgres

# make database name neetcloud and set user and password
ENV POSTGRES_USER neetcloud
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB neetcloud

# install nginx
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y nginx mc htop

# install Node.js 16
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# install Java 18
RUN apt-get install -y openjdk-17-jdk

# copy the nginx config file to the image
COPY /nginx/nginx.conf /etc/nginx/nginx.conf

# copy the frontend dir from the project to the image
COPY /client/build/ /client/build/
COPY /client/front-server.js /client/front-server.js
COPY /client/node_modules/ /client/node_modules/

# COPY the backend build from the project to the image
COPY /server/target/api-*.jar /server/backend.jar

# copy the start-script the frontend server
COPY /docker/start-frontend.sh /usr/local/bin/start-frontend
RUN chmod +x /usr/local/bin/start-frontend

# copy the start-script the backend server
COPY /docker/start-backend.sh /usr/local/bin/start-backend
RUN chmod +x /usr/local/bin/start-backend

# open port 5432, 8080, 8081
EXPOSE 5432 8080 8081

# create a directory for the database
VOLUME /data/db

# start postgresql
CMD ["postgres"]


